services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/project
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - postgres-service
        networks:
            - nginx-php-postgres
    php-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/project
        networks:
            - nginx-php-postgres
    postgres-service:
        image: postgres
        container_name: postgres-container
        ports:
            - "3306:3306"
        volumes:
            - ./var/postgres:/var/lib/postgres
        environment:
          POSTGRES_PASSWORD: postgres
        restart: always # always restart unless stopped manually
        networks:
            - nginx-php-postgres
    adminer-service:
        image: adminer
        restart: always
        ports:
          - 8081:8080
        networks:
          - nginx-php-postgres
networks:
    nginx-php-postgres: